USE CHINOOK;
SELECT 
FIRSTNAME, LASTNAME, COMPANY, STATE,
COUNT(*) OVER(PARTITION BY STATE) AS DETAILS,
CONCAT(FIRSTNAME, LASTNAME) AS FULLNAME
FROM CUSTOMER;

# FINDING DUPLICATES THROUG > 1 

SELECT * FROM (
    SELECT 
        FirstName, 
        LastName, 
        Company, 
        State,
        -- This counts how many customers are in the same state
        COUNT(CustomerId) OVER(PARTITION BY State) AS state_count,
        CONCAT(FirstName, ' ', LastName) AS FullName
    FROM customer
) AS customer_subquery
WHERE state_count > 1; -- Use the name you created inside!

# QUES:  CUSTOMER WITH SAME CUSTOMER NAME
SELECT 
    FirstName, 
    LastName, 
    COUNT(*) AS occurrence_count
FROM customer
GROUP BY FirstName, LastName
HAVING COUNT(*) > 1;

# QUES: FIND SAME NAME LAST NAMES CUSTOMERS (USING EACH ROW) 
SELECT * FROM (
    SELECT 
        CustomerId, 
        FirstName, 
        LastName,
        COUNT(*) OVER(PARTITION BY FirstName, LastName) AS name_occurrence
    FROM customer
) AS sub
WHERE name_occurrence > 1
ORDER BY LastName, FirstName;

# QUES: "Some customers might have accidental spaces at the beginning or end of their names. 
#       --Write a query using a subquery to find any duplicate name pairs after cleaning up 
#       --those extra spaces."
SELECT 
CLEANFIRSTNAME,
CLEANLASTNAME, 
COUNT(*) AS OCCURRENCE_COUNT
FROM
  (  
  SELECT
	TRIM(FirstName) AS CleanFirstName, 
	TRIM(LastName) AS CleanLastName, 
    COUNT(*) 
FROM customer
GROUP BY CleanFirstName, CleanLastName
HAVING COUNT(*) > 1
) 
AS SUB
GROUP BY CLEANFIRSTNAME, CLEANLASTNAME
HAVING COUNT(*) > 1;


###### SUM WINDOW FUNCTION   ###
##### COMPARISION ANALYSIS #####
# QUES: SEE THE PERCENTAGE OF CONTRIBUTION OF EACH CUSTOMER
SELECT 
CUSTOMERID,
BILLINGCOUNTRY,
TOTAL,
SUM(TOTAL) OVER() TOTALSALES,
SUM(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY ORDER BY TOTAL) AS TOTALAMNT,
ROUND(CAST(TOTAL AS FLOAT) / SUM(TOTAL) OVER() * 100, 2) AS PERCENTSHARE
FROM INVOICE
ORDER BY PERCENTSHARE DESC;


######## AVG FUCNITON #######
									#AVG(COALESCE(TOTAL,0)) OVER() TOTALAVGNONULLNEW#
SELECT 
*
FROM 
(SELECT 
CUSTOMERID, BILLINGCOUNTRY, TOTAL,
avg(TOTAL) OVER() AS TOTALAVG,
coalesce(TOTAL, 0) TOTALNONULL
FROM INVOICE
) AS SUB
WHERE TOTAL > TOTALAVG ORDER BY TOTAL DESC;


#### MIN AND MAX
SELECT
TOTAL, CUSTOMERID, BILLINGCOUNTRY,
MAX(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY) MAXTOTALAMNT
 FROM INVOICE
 ORDER BY MAXTOTALAMNT DESC;
 

SELECT
TOTAL, CUSTOMERID, BILLINGCOUNTRY,
MIN(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY) MINTOTALAMNT
 FROM INVOICE
 ORDER BY MAXTOTALAMNT DESC;


# QUES: SHOW CUSTOMER WITH HIGHEST BILL. FIND THE RELEVANT DATA FILTERING ALL THE TABLES. BE SPECIFIC.

SELECT
* FROM
(
SELECT
*,
MAX(TOTAL) OVER() HIGHESTTOTAL
 FROM INVOICE
 ) AS SUB
 WHERE TOTAL = HIGHESTTOTAL; #--NOTE THAT HERE WE WERE NOT ABLE TO USE WINDOW INSIDE WINDOW FUNCTION SO WE USED SUBQUERY
                         
# QUES: FIND THE DEVIATION FROM THE MAX AND MIN TOTAL SALES/BILLS

SELECT
TOTAL, CUSTOMERID, BILLINGCOUNTRY,
MIN(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY) MINTOTALAMNT,
MAX(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY) MAXTOTALAMNT,
TOTAL - MIN(TOTAL) OVER() AS DEVFROM_MIN,
MAX(TOTAL) OVER() - TOTAL AS DEVFROM_MAX 
 FROM INVOICE;
							
####### RUNNING AND ROLLING TOTAL #########
# RUNNING TOTAL GOOD FOR TRACKING BUDGET, CURRENT TOTAL SALES WITH TARGET
# ROLLING TOTAL GOOD FOR SPECIFIC OUTPUT FROM TIME FRAME OR OTHER VARIABLES, GOOD FOR FOCUSED ANALYSIS
# ques: CALCULATE THE MOVING AVG OF TOTAL BILL OVER THE TIME, INCLUDING ONLY THE NEXT TOTAL OR BILL

SELECT 
BILLINGCOUNTRY, CUSTOMERID, TOTAL, 
ROUND(AVG(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY ORDER BY CUSTOMERID), 2) AS RUNNING_TOTAL  #--USES DEFAULT UNBOUNDED ROWS
FROM INVOICE;

SELECT 
BILLINGCOUNTRY, CUSTOMERID, TOTAL, 
ROUND(AVG(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY ORDER BY CUSTOMERID ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ), 2) AS ROLLING_TOTAL 
FROM INVOICE;

# ques: CALCULATE THE MOVING AVG OF TOTAL BILL OVER THE TIME, INCLUDING ONLY THE NEXT TOTAL OR BILL
# UNITIN BOTH QUERRIES WE GET :
SELECT 
BILLINGCOUNTRY, CUSTOMERID, TOTAL, 
ROUND(AVG(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY ORDER BY CUSTOMERID), 2) AS RUNNING_TOTAL,  #--USES DEFAULT UNBOUNDED ROWS
ROUND(AVG(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY ORDER BY CUSTOMERID ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ), 2) AS ROLLING_TOTAL,
ROUND(AVG(TOTAL) OVER(PARTITION BY BILLINGCOUNTRY ORDER BY CUSTOMERID ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING ), 2) AS NEXTINCL_MOVING_AVG 
FROM INVOICE;
